name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Write value to Properties-file
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './src/main/resources/application.properties'
          property: |
            'spring.data.mongodb.uri'
            'spring.data.mongodb.database'
            'spring.security.oauth2.client.registration.google.client-id'
            'spring.security.oauth2.client.registration.google.client-secret'
            'holidays_api_key'
          value: |
            ${{ secrets.MONGODB_URI }}
            ${{ secrets.MONGODB_DATABASE }}
            ${{ secrets.CLIENT_ID }}
            ${{ secrets.CLIENT_SECRET }}
            ${{ secrets.HOLIDAYS_API_KEY }}

      - name: Build with Maven
        run: mvn clean install
